name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 编译服务端程序 (Linux 版本)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Server Binary
        run: |
          # 自动初始化 go.mod (如果不存在 )
          if [ ! -f go.mod ]; then
            go mod init server
          fi
          go mod tidy || true
          
          # 编译成 Linux 版本的 amd64 二进制文件
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o myapp .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
